### PR TITLE
Updated to chartist 0.8

### PR DESCRIPTION
**Pull request by b123400**

### CODE REVIEW

**Comment by tylergaw** [comment]
ugh, I'm the worst. Have not had a free moment to look into this.

We'll have to get the build/tests passing before we can merge this. Not sure what yet, but something has changed that's causing the build to fail

**Comment by samselikoff** [comment]
Once you fix shall we use #36 instead of keeping the chartist dist in this addon?

**Comment by samselikoff** [comment]
Woops, #30. didn't even see.

**Comment by tylergaw** [comment]
@b123400 Sorry for the delay. I have a branch open #39 for updating to Chartist 0.9.x. It's requiring more work. I'm going to close this.

Thank you for submitting this though.

**Pull request closed without merging**
